### ISSUE TITLE
Got Javac error 

### ISSUE THREAD

**Issue by sneevand** [DanielCauser/SocialLoginSamples#2]
Severity	Code	Description	Project	File	Line	Suppression State
Error		The "Javac" task failed unexpectedly.
System.IO.PathTooLongException: The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.
   at System.IO.LongPathHelper.Normalize(String path, UInt32 maxPathLength, Boolean checkInvalidCharacters, Boolean expandShortPaths)
   at System.IO.Path.NewNormalizePath(String path, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.Path.GetFullPathInternal(String path)
   at System.IO.FileInfo.Init(String fileName, Boolean checkHost)
   at System.IO.FileInfo..ctor(String fileName)
   at Xamarin.Android.Tasks.ZipArchiveEx.AddFiles(String folder, String folderInArchive)
   at Xamarin.Android.Tasks.ZipArchiveEx.AddDirectory(String folder, String folderInArchive)
   at Xamarin.Android.Tasks.Javac.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()	GoogleNativeLogin.Droid

**Comment by sneevand** [comment]
strange just copied  the project   under c drive without sub folders works fine.

**Comment by DanielCauser** [comment]
Yeah, I have got this error before, Just place the project folder closer to the drive root you are using.

=D
