### ISSUE TITLE
Error - Lcom/google/android/gms/common/api/zzf

### ISSUE THREAD

**Issue by rodrigueslg** [DanielCauser/SocialLoginSamples#7]
Did you get this error? I'm facing this error on your example and on my project, after implement the Google auth. I already activated multi-dex, but the error continues.

java.lang.IllegalArgumentException: already added :  Lcom/google/android/gms/common/api/zzf;	GoogleNativeLogin.Droid

UNEXPECTED TOP-LEVEL EXCEPTION:
2>  java.lang.RuntimeException: Translation has been interrupted
2>  	at com.android.dx.command.dexer.Main.processAllFiles(Main.java:615)
2>  	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:313)
2>  	at com.android.dx.command.dexer.Main.runDx(Main.java:291)
2>  	at com.android.dx.command.dexer.Main.main(Main.java:247)
2>  	at com.android.dx.command.Main.main(Main.java:94)
2>  Caused by: java.lang.InterruptedException: Too many errors
2>  	at com.android.dx.command.dexer.Main.processAllFiles(Main.java:607)

**Comment by DanielCauser** [comment]
Hey, I will take a look at this as soon as I can, if you find n answer let me know!

**Comment by BillyMartin1964** [comment]
I'm getting the same error and I don't use your plugin! Must be something in the Android support packages

**Comment by EmilAlipiev** [comment]
are you using proguard? if not add a proguard into your app and enable it
